import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'language': 'English',
          'str_hindi':'हिंदी',
          'select_lang':'Select Language',
          'str_english':'English',
          'str_language':'Languages',
          'home':'Home',
          'my_orders':'My Orders',
          'cart':'Cart',
          'account':'account',
          'products':'Products',
          'profile':'My Profile',
          'shipping_address':'Shipping Address',
          'pay_methods':'Payment Methods',
          'promo':'Promocodes',
          'my_reviews':'My Reviews',
          'settings':'Settings',
          'logout':'Logout',
          'select_address':'Select Address',
          'add_address':'Add New Address',
          'cancel':'Cancel',
          'delivery_address_btn':'Deliver to this Address',
          'edit_address':'Edit Address',
          'add_address_btn':'Use this Address',
          'full_name':'Full Name(First and Last Name)',
          'full_name_hint':'Enter Full Name',
          'mobile_no':'Mobile Number',
          'mobile_hint':'Enter Mobile Number',
          'flat_no.':'Flat, House no., Building, Company, Apartment',
          'flat_no_hint':'Enter Plot No.',
          'area':'Area,Street, Sector, Village',
          'area_hint':'Enter Area, Street',
          'landmark':'Landmark',
          'landmark_hint':'E.g. near Apollo Hospital',
          'pin_code':'Pincode',
          'pin_code_hint':'6-digit Pincode',
          'city':'Town/City',
          'city_hint':'E.g. Nagpur',
          'state':'State',
          'state_hint':'E.g. Maharashtra',
        },
        'hi_IN': {
          'language': 'हिंदी',
          'str_language':'भाषा',
          'select_lang':'भाषा चुने',
          'str_hindi':'हिंदी',
          'str_english':'English',
          'home':'घर',
          'my_orders':'मेरी खरीदारी',
          'cart':'कार्ट',
          'account':'मेरी प्रोफाइल',
          'products':'उत्पादों',
          'profile':'मेरी खरीदारी',
          'shipping_address':'शिपिंग पता',
          'pay_methods':'भुगतान की विधि',
          'promo':'प्रोमो कोड',
          'my_reviews':'मेरी समीक्षाएँ',
          'settings':'सेटिंग',
          'logout':'लॉग आउट',
          'select_address':'पता चुनें',
          'add_address':'नया पता जोड़ें',
          'cancel':'रद्द करना',
          'delivery_address_btn':'इस पते पर पहुंचाएं',
          'edit_address':'पता संपादित करें',
          'add_address_btn':'पता संपादित करें',
          'full_name':'पूरा नाम (पहला और अंतिम नाम)',
          'full_name_hint':'पूरा नाम दर्ज करें',
          'mobile_no':'मोबाइल नंबर',
          'mobile_hint':'मोबाइल नंबर दर्ज करें',
          'flat_no.':'फ्लैट, मकान नंबर, बिल्डिंग, कंपनी, अपार्टमेंट',
          'flat_no_hint':'प्लॉट नंबर दर्ज करें.',
          'area':'क्षेत्र, सड़क, सेक्टर, गांव',
          'area_hint':'क्षेत्र, सड़क दर्ज करें',
          'landmark':'सीमाचिह्न',
          'landmark_hint':'जैसे अपोलो अस्पताल के पास',
          'pin_code':'पिन कोड',
          'pin_code_hint':'6 अंकीय पिनकोड',
          'city':'नगर/शहर',
          'city_hint':'जैसे नागपुर',
          'state':'राज्य',
          'state_hint':'जैसे महाराष्ट्र',
        },
      };
}
